apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
    patch: | 
      - op: replace
        path: /metadata/name
        value: {{ .Values.name }}
      - op: replace
        path: /spec/template/metadata/labels/app
        value: {{ .Values.name }}
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: {{ .Values.name }}
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: docker.io/jmartinezblanco/{{ .Values.name }}

